#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, '..');
const GIT_HOOKS_DIR = path.join(PROJECT_ROOT, '.git', 'hooks');
const POST_COMMIT_HOOK = path.join(GIT_HOOKS_DIR, 'post-commit');

const hookScript = `#!/bin/sh
# Supermemory change tracker - Auto-generated by install-hooks.js
# This hook runs after every commit to track changes in Supermemory

echo "Syncing commit to Supermemory..."
cd supermemory-integration
node track-changes.js &
cd ..
`;

function installHook() {
  console.log('Installing git post-commit hook...\n');

  // Check if .git directory exists
  if (!fs.existsSync(path.join(PROJECT_ROOT, '.git'))) {
    console.error('Error: Not a git repository');
    console.error('   Run this from the root of your git project');
    process.exit(1);
  }

  // Create hooks directory if it doesn't exist
  if (!fs.existsSync(GIT_HOOKS_DIR)) {
    fs.mkdirSync(GIT_HOOKS_DIR, { recursive: true });
  }

  // Check if hook already exists
  if (fs.existsSync(POST_COMMIT_HOOK)) {
    const existing = fs.readFileSync(POST_COMMIT_HOOK, 'utf8');
    if (existing.includes('Supermemory')) {
      console.log('Hook already installed');
      return;
    }

    // Backup existing hook
    const backupPath = POST_COMMIT_HOOK + '.backup';
    fs.copyFileSync(POST_COMMIT_HOOK, backupPath);
    console.log(`Backed up existing hook to: ${path.basename(backupPath)}`);
  }

  // Write hook
  fs.writeFileSync(POST_COMMIT_HOOK, hookScript, { mode: 0o755 });

  console.log('Git hook installed successfully!');
  console.log(`Location: .git/hooks/post-commit\n`);
  console.log('Setup complete! Now every commit will be tracked in Supermemory.');
  console.log('\nNext steps:');
  console.log('  1. Make a commit to test: git commit -m "Test commit"');
  console.log('  2. Check logs to see the sync happen');
  console.log('  3. Query your codebase: npm run query\n');
}

installHook();

